context:
  version: "15.2.0"

package:
  name: syncpack
  version: ${{ version }}

source:
  url: https://github.com/JamieMason/syncpack/archive/refs/tags/${{ version }}.tar.gz
  sha256: 37066b7c255c562b156693da6c972e2eef25aa7648bedf7abf901b87600e8cbe

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - syncpack --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Consistent dependency versions in large JavaScript Monorepos.
  homepage: https://github.com/JamieMason/syncpack
  repository: https://github.com/JamieMason/syncpack

extra:
  recipe-maintainers:
    - danielnachun
