context:
  version: "13.0.3"

package:
  name: syncpack
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/syncpack/-/syncpack-${{ version }}.tgz
  sha256: dfc579124b824329a9fe3a1842f4c3298dc70276b242d9e3fc4e06ef66261f59

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - syncpack --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Consistent dependency versions in large JavaScript Monorepos.
  homepage: https://github.com/JamieMason/syncpack
  repository: https://github.com/JamieMason/syncpack

extra:
  recipe-maintainers:
    - danielnachun
