context:
  version: "14.0.0"

package:
  name: syncpack
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/syncpack/-/syncpack-${{ version }}.tgz
  sha256: 03e9c612bede3e68a12f2b8e36f896355c2ca82abd45a6fe67957e706b8696bf

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - syncpack --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Consistent dependency versions in large JavaScript Monorepos.
  homepage: https://github.com/JamieMason/syncpack
  repository: https://github.com/JamieMason/syncpack

extra:
  recipe-maintainers:
    - danielnachun
