context:
  version: "14.0.1"

package:
  name: syncpack
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/syncpack/-/syncpack-${{ version }}.tgz
  sha256: acbb8e75a9db82b04d4d43c2d2b88faf594d4a0b6a216421df8ebe6fceea7bda

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - syncpack --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Consistent dependency versions in large JavaScript Monorepos.
  homepage: https://github.com/JamieMason/syncpack
  repository: https://github.com/JamieMason/syncpack

extra:
  recipe-maintainers:
    - danielnachun
